testing

diff --git a/build b/build
--- a/build
+++ b/build
@@ -1,3 +1,5 @@
+echo "running: $0 $*" && set -eu && set -o pipefail && set -x && trap "echo 'ERR' && exit -1" ERR
+
 node {
    echo 'Hello World santosh'
 }
